Fix syntax in doc deploy action.
Rename CI testing yml to actions-CI-tests.yml
Add notebook test to code coverage report. Update requirements with pytest-cov.

diff --git a/.github/workflows/actions-CI-tests.yml b/.github/workflows/actions-CI-tests.yml
--- a/.github/workflows/actions-CI-tests.yml
+++ b/.github/workflows/actions-CI-tests.yml
@@ -25,10 +25,10 @@ jobs:
     - name: Install dependencies
       run: |
         sudo apt-get -qq update
-        sudo apt-get install -y pandoc # for markdown notebook cells
+        sudo apt-get install -y pandoc  # for markdown notebook cells
         python -m pip install --upgrade pip
         pip install flake8 pytest
-        pip install . # install package with requirements
+        pip install .  # install package with requirements
         pip install -r requirements-dev.txt
     - name: Lint with flake8
       run: |
@@ -38,9 +38,10 @@ jobs:
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Test with pytest & nbval
       run: |
+        set -e  # exit on error
         coverage run -m pytest  # Run the tests and check for test coverage.
+        python -m ipykernel install --user
+        # Test tutorial notebook execution:
+        pytest --timeout=180 --cov-append --nbval-lax --current-env ./emgfit/examples/tutorial/emgfit_tutorial.ipynb
         coverage report -m  # Generate test coverage report.
         codecov  # Upload the report to codecov.
-        python -m ipykernel install --user
-        set -e # exit on error
-        py.test --timeout=180 --nbval-lax --current-env ./emgfit/examples/tutorial/emgfit_tutorial.ipynb # test tutorial notebook execution
